import { createFileRoute } from "@tanstack/react-router";
import { useMemo, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { toast } from "sonner";
import { supabase } from "@/integrations/supabase/client";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { formatMZN } from "@/lib/format";
import { AlertTriangle, ArrowDownLeft, ArrowUpRight, Search, ShieldCheck, Sparkles, Users, WalletCards } from "lucide-react";
import { useStaff } from "./route";

export const Route = createFileRoute("/_authenticated/staff/")({ head:()=>({meta:[{title:"Painel Admin · Villa Card Rewards"},{name:"description",content:"Gestão de clientes, cartões, transações e fidelidade Villa Card."}]}), component: StaffDashboard });

type Cliente={id:string;nome:string;contacto:string|null;email:string|null;data_registo:string;cartao_nfc_id:string|null;saldo_atual:number;tier:string};
type Cartao={id:string;cliente_id:string;codigo_nfc:string;estado:"ativo"|"bloqueado"|"perdido";data_emissao:string};
type Tx={id:string;cliente_id:string;tipo:string;valor:number;saldo_apos:number;descricao:string|null;timestamp:string};
type Vantagem={id:string;nome:string;descricao:string|null;tier_minimo:string;tipo_desconto:string;valor_desconto:number};
type Nivel={id:string;nome:string;ordem:number;desconto_percentual:number;descricao:string|null;ativo:boolean};

function StaffDashboard(){
 const {data:staff}=useStaff(); const qc=useQueryClient(); const [busca,setBusca]=useState(""); const [clienteId,setClienteId]=useState<string|null>(null); const [tierAlert,setTierAlert]=useState<string|null>(null);
 const clientes=useQuery({queryKey:["admin-clientes"],queryFn:async()=>{const {data,error}=await supabase.from("clientes").select("*").order("nome");if(error)throw error;return data as Cliente[];}});
 const cartoes=useQuery({queryKey:["admin-cartoes"],queryFn:async()=>{const {data,error}=await supabase.from("cartoes").select("*").order("data_emissao",{ascending:false});if(error)throw error;return data as Cartao[];}});
 const tx=useQuery({queryKey:["admin-tx"],queryFn:async()=>{const {data,error}=await supabase.from("transacoes").select("*").order("timestamp",{ascending:false}).limit(500);if(error)throw error;return data as Tx[];}});
 const vantagens=useQuery({queryKey:["admin-vantagens"],queryFn:async()=>{const {data,error}=await supabase.from("vantagens").select("*").order("nome");if(error)throw error;return data as Vantagem[];}});
 const niveis=useQuery({queryKey:["admin-niveis"],queryFn:async()=>{const {data,error}=await supabase.from("niveis_fidelidade").select("*").order("ordem");if(error)throw error;return data as Nivel[];}});
 const hoje=new Date(); const inicioDia=new Date(hoje);inicioDia.setHours(0,0,0,0); const inicioMes=new Date(hoje.getFullYear(),hoje.getMonth(),1);
 const metricas=useMemo(()=>({cartoes:cartoes.data?.filter(c=>c.estado==="ativo").length??0,saldo:(clientes.data??[]).reduce((s,c)=>s+Number(c.saldo_atual),0),dia:(tx.data??[]).filter(t=>new Date(t.timestamp)>=inicioDia).length,mes:(tx.data??[]).filter(t=>new Date(t.timestamp)>=inicioMes).length,novos:(clientes.data??[]).filter(c=>new Date(c.data_registo)>=inicioMes).length}),[clientes.data,cartoes.data,tx.data]);
 const lista=(clientes.data??[]).filter(c=>{const q=busca.toLowerCase().trim();return !q||c.nome.toLowerCase().includes(q)||(c.contacto??"").includes(q)||(c.email??"").toLowerCase().includes(q)});
 const selecionado=lista.find(c=>c.id===clienteId)??null;
 if(!staff)return null;
 return <main className="mt-6 space-y-8">{tierAlert&&<div className="rounded-2xl border border-primary/30 bg-primary/10 p-4 text-sm"><b>✨ Subida de tier:</b> {tierAlert}<button className="ml-3 underline" onClick={()=>setTierAlert(null)}>Fechar</button></div>}
   <section><div className="flex items-end justify-between"><div><p className="text-xs uppercase tracking-[0.25em] text-primary">Admin / Staff</p><h2 className="mt-1 text-2xl sm:text-3xl">Dashboard</h2></div><span className="flex items-center gap-2 text-xs text-muted-foreground"><ShieldCheck className="size-4 text-primary"/>Acesso protegido por Auth + RLS</span></div>
    <div className="mt-5 grid grid-cols-2 gap-3 lg:grid-cols-5">{[
      ["Cartões activos",String(metricas.cartoes),WalletCards],["Saldo em circulação",formatMZN(metricas.saldo),WalletCards],["Transações hoje",String(metricas.dia),ArrowUpRight],["Transações este mês",String(metricas.mes),ArrowDownLeft],["Novos clientes",String(metricas.novos),Users]
    ].map(([label,value,Icon])=><div key={String(label)} className="card-premium rounded-2xl p-4"><Icon className="size-5 text-primary"/><p className="mt-4 text-xs text-muted-foreground">{label}</p><p className="mt-1 text-xl font-medium">{value}</p></div>)}</div>
   </section>
   <section className="grid gap-6 lg:grid-cols-[1.2fr_0.8fr]">
    <div className="card-premium rounded-3xl p-5"><div className="flex items-center justify-between gap-3"><div><h2 className="text-xl">Clientes</h2><p className="text-sm text-muted-foreground">Pesquisar e consultar histórico individual.</p></div></div><div className="relative mt-4"><Search className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-9" placeholder="Nome, contacto ou email" value={busca} onChange={e=>setBusca(e.target.value)}/></div><div className="mt-4 max-h-96 space-y-2 overflow-y-auto">{lista.map(c=><button key={c.id} onClick={()=>setClienteId(c.id)} className={`w-full rounded-2xl border p-4 text-left ${clienteId===c.id?"border-primary bg-primary/10":"border-border bg-card/50"}`}><div className="flex justify-between gap-3"><span className="font-medium">{c.nome}</span><span className="text-sm">{formatMZN(c.saldo_atual)}</span></div><p className="mt-1 text-xs text-muted-foreground">{c.contacto??"Sem contacto"} · {c.tier}</p></button>)}{!lista.length&&<p className="p-6 text-center text-sm text-muted-foreground">Nenhum cliente encontrado.</p>}</div></div>
    <ClienteHistorico cliente={selecionado} tx={tx.data??[]}/>
   </section>
   <section><h2 className="text-xl">Registo de transação</h2><p className="text-sm text-muted-foreground">Digite o código NFC manualmente para simular a leitura do cartão.</p><TransacaoForm clientes={clientes.data??[]} onDone={()=>{qc.invalidateQueries({queryKey:["admin-clientes"]});qc.invalidateQueries({queryKey:["admin-tx"]});}}/></section>
   <section className="grid gap-6 lg:grid-cols-2"><GestaoNiveis niveis={niveis.data??[]} onDone={()=>qc.invalidateQueries({queryKey:["admin-niveis"]})}/><GestaoVantagens vantagens={vantagens.data??[]} niveis={niveis.data??[]} onDone={()=>qc.invalidateQueries({queryKey:["admin-vantagens"]})}/></section>
 </main>;
}

function ClienteHistorico({cliente,tx}:{cliente:Cliente|null;tx:Tx[]}){if(!cliente)return <div className="card-premium grid min-h-64 place-items-center rounded-3xl p-6 text-center text-sm text-muted-foreground">Seleccione um cliente para ver o histórico individual.</div>;const rows=tx.filter(t=>t.cliente_id===cliente.id).slice(0,30);return <div className="card-premium rounded-3xl p-5"><h2 className="text-xl">{cliente.nome}</h2><p className="text-sm text-muted-foreground">Histórico individual · {cliente.tier} · {formatMZN(cliente.saldo_atual)}</p><div className="mt-4 space-y-2 max-h-80 overflow-y-auto">{rows.map(t=><div key={t.id} className="flex justify-between gap-3 rounded-xl border border-border p-3"><div><p className="text-sm">{t.descricao??t.tipo}</p><p className="text-xs text-muted-foreground">{new Date(t.timestamp).toLocaleString("pt-PT")}</p></div><div className="text-right"><p className="text-sm">{t.tipo==="recarga"?"+":"−"} {formatMZN(t.valor)}</p><p className="text-xs text-muted-foreground">{formatMZN(t.saldo_apos)}</p></div></div>)}{!rows.length&&<p className="p-6 text-center text-sm text-muted-foreground">Sem transações.</p>}</div></div>}

function TransacaoForm({clientes,onDone}:{clientes:Cliente[];onDone:()=>void}){const [codigo,setCodigo]=useState("");const [tipo,setTipo]=useState("consumo");const [valor,setValor]=useState("");const [cliente,setCliente]=useState<Cliente|null>(null);const [loading,setLoading]=useState(false);
 async function procurar(){const {data,error}=await supabase.from("cartoes").select("cliente_id,estado").eq("codigo_nfc",codigo.trim()).maybeSingle();if(error)toast.error(error.message);else if(!data)toast.error("Cartão NFC não encontrado.");else if(data.estado!=="ativo")toast.error(`Cartão ${data.estado}.`);else setCliente(clientes.find(c=>c.id===data.cliente_id)??null);}
 async function registar(){if(!cliente||Number(valor)<=0)return;setLoading(true);try{const fn=tipo==="recarga"?"registar_recarga":"registar_consumo";const {error}=await supabase.rpc(fn,{_cliente_id:cliente.id,...(tipo==="recarga"?{_valor:Number(valor),_descricao:"Recarga via painel staff"}:{_valor_bruto:Number(valor),_descricao:"Consumo via painel staff"})});if(error)throw error;toast.success("Transação registada.");setValor("");setCliente(null);setCodigo("");onDone();}catch(e){toast.error("Transação não registada",{description:(e as Error).message});}finally{setLoading(false)}}return <div className="card-premium mt-4 rounded-3xl p-5"><div className="grid gap-4 md:grid-cols-[1.2fr_auto_1fr_auto] md:items-end"><div><Label>Código NFC</Label><Input className="mt-2" value={codigo} onChange={e=>setCodigo(e.target.value)} placeholder="Ex.: VILLA-000123"/></div><Button variant="outline" onClick={procurar} disabled={!codigo}>Ler cartão</Button><div><Label>Tipo</Label><Select value={tipo} onValueChange={setTipo}><SelectTrigger className="mt-2"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="consumo">Consumo</SelectItem><SelectItem value="recarga">Recarga</SelectItem></SelectContent></Select></div><div><Label>Valor (MZN)</Label><Input className="mt-2" type="number" min="1" value={valor} onChange={e=>setValor(e.target.value)}/></div></div>{cliente&&<div className="mt-4 flex flex-wrap items-center justify-between gap-3 rounded-2xl border border-primary/30 bg-primary/5 p-4"><div><p className="font-medium">{cliente.nome}</p><p className="text-xs text-muted-foreground">Tier {cliente.tier} · Saldo {formatMZN(cliente.saldo_atual)}{tipo==="consumo"?" · desconto aplicado automaticamente":""}</p></div><Button className="surface-gold" onClick={registar} disabled={loading}>{loading?"A registar…":"Confirmar transação"}</Button></div>}</div>}

function GestaoNiveis({niveis,onDone}:{niveis:Nivel[];onDone:()=>void}){const [nome,setNome]=useState("");const [desc,setDesc]=useState("");const [desconto,setDesconto]=useState("0");const [ordem,setOrdem]=useState(String(niveis.length+1));const mut=useMutation({mutationFn:async()=>{const {error}=await supabase.from("niveis_fidelidade").insert({nome:nome.toLowerCase(),descricao:desc||null,desconto_percentual:Number(desconto),ordem:Number(ordem)});if(error)throw error},onSuccess:()=>{toast.success("Nível criado.");setNome("");setDesc("");setDesconto("0");onDone()},onError:e=>toast.error("Não foi possível criar o nível",{description:e.message})});return <div className="card-premium rounded-3xl p-5"><div className="flex items-center gap-2"><Sparkles className="size-5 text-primary"/><div><h2 className="text-xl">Níveis de fidelidade</h2><p className="text-sm text-muted-foreground">Criar níveis e definir desconto automático.</p></div></div><div className="mt-4 space-y-2">{niveis.map(n=><div key={n.id} className="flex justify-between rounded-xl border border-border p-3 text-sm"><span>{n.nome}</span><span>{n.desconto_percentual}% · ordem {n.ordem}</span></div>)}</div><div className="mt-5 grid gap-3 sm:grid-cols-2"><Input placeholder="Nome do nível" value={nome} onChange={e=>setNome(e.target.value)}/><Input type="number" min="0" max="100" placeholder="Desconto %" value={desconto} onChange={e=>setDesconto(e.target.value)}/><Input placeholder="Descrição" value={desc} onChange={e=>setDesc(e.target.value)}/><Input type="number" min="1" placeholder="Ordem" value={ordem} onChange={e=>setOrdem(e.target.value)}/></div><Button className="surface-gold mt-4 w-full" disabled={!nome||mut.isPending} onClick={()=>mut.mutate()}>Criar nível</Button></div>}

function GestaoVantagens({vantagens,niveis,onDone}:{vantagens:Vantagem[];niveis:Nivel[];onDone:()=>void}){const [nome,setNome]=useState("");const [descricao,setDescricao]=useState("");const [tier,setTier]=useState(niveis[0]?.nome??"bronze");const [tipo,setTipo]=useState("percentual");const [valor,setValor]=useState("0");const mut=useMutation({mutationFn:async()=>{const {error}=await supabase.from("vantagens").insert({nome,descricao:descricao||null,tier_minimo:tier,tipo_desconto:tipo,valor_desconto:Number(valor)});if(error)throw error},onSuccess:()=>{toast.success("Vantagem criada.");setNome("");setDescricao("");setValor("0");onDone()},onError:e=>toast.error("Não foi possível criar a vantagem",{description:e.message})});return <div className="card-premium rounded-3xl p-5"><div className="flex items-center gap-2"><Sparkles className="size-5 text-primary"/><div><h2 className="text-xl">Vantagens</h2><p className="text-sm text-muted-foreground">Criar benefícios associados ao tier mínimo.</p></div></div><div className="mt-4 space-y-2">{vantagens.map(v=><div key={v.id} className="rounded-xl border border-border p-3 text-sm"><div className="flex justify-between"><span>{v.nome}</span><span>{v.valor_desconto}{v.tipo_desconto==="percentual"?"%":""}</span></div><p className="text-xs text-muted-foreground">Tier mínimo: {v.tier_minimo} · {v.descricao??""}</p></div>)}</div><div className="mt-5 space-y-3"><Input placeholder="Nome da vantagem" value={nome} onChange={e=>setNome(e.target.value)}/><Input placeholder="Descrição" value={descricao} onChange={e=>setDescricao(e.target.value)}/><div className="grid grid-cols-2 gap-3"><Select value={tier} onValueChange={setTier}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{niveis.map(n=><SelectItem key={n.id} value={n.nome}>{n.nome}</SelectItem>)}</SelectContent></Select><Input type="number" min="0" placeholder="Valor do desconto" value={valor} onChange={e=>setValor(e.target.value)}/></div><Button className="surface-gold w-full" disabled={!nome||mut.isPending} onClick={()=>mut.mutate()}>Criar vantagem</Button></div></div>}
